#C'est pour faire des filtres photos
# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  twig:
    mode: lazy
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "imagick"
  filter_sets:
    # the name of the "filter set"
    my_thumb:
      # adjust the image quality to 75%
      quality: 75

      # list of transformations to apply (the "filters")
      filters:
        # create a thumbnail: set size to 120x90 and use the "outbound" mode
        # to crop the image when the size ratio of the input differs
        thumbnail: { size: [120, 90], mode: outbound }
        # create a 2px black border: center the thumbnail on a black background
        # 4px larger to create a 2px border around the final image
        background: { size: [124, 94], position: center, color: "#000000" }
