#Sert à ulpoader des images
vich_uploader:
  db_driver: orm
  mappings:
    profile_image:
      uri_prefix: /uploads/profile_images
      upload_destination: "%kernel.project_dir%/public/uploads/profile_images"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    event_image:
      uri_prefix: /uploads/event_images
      upload_destination: "%kernel.project_dir%/public/uploads/event_images"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
